language: java
cache:
  directories:
  - $HOME/.m2
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
script: mvn clean install
after_success:
  - mvn jacoco:report
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r omod/target/site/jacoco/jacoco.xml
  - bash <(curl -s https://codecov.io/bash)